<Project><PropertyGroup><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><LangVersion>latest</LangVersion><RestorePackagesWithLockFile>true</RestorePackagesWithLockFile><Deterministic>true</Deterministic><WindowsSdkPackageVersion>10.0.22621.57</WindowsSdkPackageVersion></PropertyGroup></Project>
