<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net10.0-windows10.0.22621.0</TargetFramework><UseWPF>true</UseWPF><ApplicationManifest>app.manifest</ApplicationManifest><ApplicationIcon>Assets/pcc.ico</ApplicationIcon><AssemblyName>PersonalControlCenter</AssemblyName><Version>0.8.0</Version></PropertyGroup><ItemGroup><ProjectReference Include="../ControlCenter.Core/ControlCenter.Core.csproj" /><ProjectReference Include="../ControlCenter.Windows/ControlCenter.Windows.csproj" /><Content Include="Assets/pcc.ico" CopyToOutputDirectory="PreserveNewest" /></ItemGroup></Project>
